### ISSUE TITLE
learn.js crashes node-red

### ISSUE THREAD

**Issue by genepool99** [denwilliams/node-red-contrib-orvibo-allone#1]
If I run learn.js with node-red running I get the followinf in the node-red log:

4 Jan 17:44:19 - [red] Uncaught Exception:
4 Jan 17:44:19 - Error: bind EADDRINUSE 0.0.0.0:10000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:218:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Node: 7.2.0
Node-red: 0.15.2
OS: Ubuntu 14.04

**Comment by genepool99** [comment]
Also, when rapidly injecting 4-5 times into the ir emitter (with a valid IR code) I get:
14 Jan 20:02:18 - [red] Uncaught Exception:
14 Jan 20:02:18 - Error: write EIO
at exports._errnoException (util.js:1022:11)
at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)

Version information:
Node: 7.2.0
Node-red:0.15.2
